<?php
namespace App\Controller;

use App\Model\ReservationModel;
use Core\Controller\DefaultController;
use Core\Security\Security;

final class ReservationController extends DefaultController
{
    public function __construct()
    {
        parent::__construct(new ReservationModel());
    }

    public function update(int $id, array $data)
    {
        if(!Security::isAuthorized()){
            self::jsonResponse(["description" => "Access Denied"], 401);
            return ;
        }

        parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function save(array $data)
    {
        if(!isset($data["email"])
            ){

        }
        parent::save($data); // TODO: Change the autogenerated stub
    }
}