<?php
namespace App\Controller;

use App\Model\TableModel;
use Core\Controller\DefaultController;
use Core\Security\Security;

final class TableController extends DefaultController
{
    public function __construct()
    {
        parent::__construct(new TableModel());
    }

    public function save(array $data)
    {
        if (!Security::isAuthorized()) {
            self::jsonResponse(["description" => "Access Denied"], 401);
            return;
        }

        parent::save($data); // TODO: Change the autogenerated stub
    }

    public function update(int $id, array $data)
    {
        if (!Security::isAuthorized()) {
            self::jsonResponse(["description" => "Access Denied"], 401);
            return;
        }

        parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete(int $id)
    {
        if (!Security::isAuthorized()) {
            self::jsonResponse(["description" => "Access Denied"], 401);
            return;
        }
        parent::delete($id); // TODO: Change the autogenerated stub
    }
}