<?php
namespace App\Controller;

use App\Model\UserModel;
use Core\Controller\DefaultController;
use Core\Security\Security;

final class UserController extends DefaultController
{
    public function __construct()
    {
        parent::__construct(new UserModel());
    }

    public function save(array $data)
    {
        if(!Security::isAuthorized()){
            self::jsonResponse(["description" => "Access Denied"], 401);
            return ;
        }

        parent::save($data); // TODO: Change the autogenerated stub
    }

    public function update(int $id, array $data)
    {
        if(!Security::isAuthorized()){
            self::jsonResponse(["description" => "Access Denied"], 401);
            return ;
        }

        parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete(int $id)
    {
        if(!Security::isAuthorized()){
            self::jsonResponse(["description" => "Access Denied"], 401);
            return ;
        }

        parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function single(int $id)
    {
        if(!Security::isAuthorized()){
            self::jsonResponse(["description" => "Access Denied"], 401);
            return ;
        }

        parent::single($id); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if(!Security::isAuthorized()){
            self::jsonResponse(["description" => "Access Denied"], 401);
            return ;
        }

        parent::index(); // TODO: Change the autogenerated stub
    }
}